# -*- coding: utf-8 -*-
"""Contenido bilingüe de Eros Studio. Edita aquí y vuelve a correr build.py."""

SITE_URL = "https://erosstudio.mx"          # <-- cambia por tu dominio real
WHATSAPP_NUMBER = "527718366618"            # +52 771 836 6618 sin espacios ni '+'
EMAIL = "habzerl753@gmail.com"
NAME = "Eros Atzin Martínez Hernández"
BRAND = "Eros Studio"
LINKEDIN = ""   # p. ej. https://www.linkedin.com/in/eros-atzin-martinez-hernandez
INSTAGRAM = ""  # p. ej. https://www.instagram.com/erosstudio

COMMON = dict(
    name=NAME, brand=BRAND, email=EMAIL, site=SITE_URL,
    wa_number=WHATSAPP_NUMBER, wa_display="+52 771 836 6618",
    linkedin=LINKEDIN, instagram=INSTAGRAM, year="2026",
)

ES = dict(
    lang="es", other_lang="EN", other_lang_label="English", other_href="en/index.html",
    prefix="", canonical=SITE_URL + "/",
    title=f"{NAME} | Eros Studio — Crecimiento digital para turismo, inmobiliaria y construcción",
    description=("Eros Atzin Martínez Hernández, fundador de Eros Studio. Ayudo a hoteles boutique, inmobiliarias y constructoras "
                 "a construir un negocio que atrae clientes de todo el mundo —presencia digital bilingüe, conexión humana y expansión "
                 "internacional— mientras tú te encargas de lo operativo. Diagnóstico gratis por WhatsApp."),
    keywords="Eros Atzin Martínez Hernández, Eros Studio, crecimiento digital, estrategia digital para inmobiliarias, marketing para constructoras, marketing para hoteles boutique, webs bilingües, clientes internacionales, Pachuca, Hidalgo, México",
    wa_msg="Hola Eros, vi tu web y quiero agendar un diagnóstico gratis para mi negocio.",
    skip="Ir al contenido",
    nav=dict(growth="Crecimiento", services="Cómo te ayudo", cases="Casos", about="Sobre mí", process="Proceso", faq="FAQ", cta="Agendar diagnóstico", menu="Menú"),
    chapters=["Inicio", "Manifiesto", "Tu situación", "Imagina", "Cómo te ayudo", "Caso real", "Sobre mí", "Proceso", "Preguntas", "Empecemos"],
    intro_aria="Cargando Eros Studio",
    hero=dict(
        eyebrow="Eros Atzin Martínez Hernández · Eros Studio",
        h1_a="Tu negocio puede atraer clientes de", h1_b="todo el mundo", h1_c="mientras tú te encargas de lo operativo.",
        sub="Para hoteles boutique, inmobiliarias y constructoras que quieren crecer más allá de su mercado local.",
        cta="Agendar diagnóstico gratis", cta2="Ver cómo funciona",
        trust=["Diagnóstico gratis de 15 minutos", "Respuesta en menos de 24 h"],
        scroll="Desliza",
        big_a="EROS", big_b="ATZIN",
        role="Estrategia · Presencia digital · Expansión",
        sig_line="No te vendo una web. Te acompaño a construir un negocio que crece.",
    ),
    trust=dict(label="Experiencia en", items=["Turismo", "Inmobiliaria", "Construcción", "Tekton Arquitectos", "Español", "Inglés", "Francés (en progreso)"],
               years="+3 años dentro del sector inmobiliario y de la construcción"),
    manifesto=dict(
        eyebrow="Manifiesto",
        text="Una web bonita no paga la nómina. Lo que paga la nómina es un negocio que la gente encuentra, en el que confía y al que le compra, aunque esté a diez mil kilómetros. Eso es lo que construimos juntos.",
        stats=[("+3", "años en inmobiliaria y construcción"), ("2", "idiomas para vender, el tercero en camino"), ("24/7", "tu negocio captando mientras tú operas")],
    ),
    problem=dict(
        eyebrow="Tu situación", title="Si alguna de estas frases suena a tu voz, sigue leyendo.",
        items=[
            ("Dependo de referidos.", "Si un mes nadie me recomienda, ese mes no entra nadie. Y no tengo forma de cambiarlo."),
            ("Mi web no me trae ni un cliente.", "La pagué, existe, pero nadie llega por ahí. Ni siquiera sé si sale en Google."),
            ("Los extranjeros no me encuentran.", "Sé que hay compradores y huéspedes internacionales con presupuesto. Pero todo lo mío está solo en español."),
            ("Pierdo horas con gente que no va a comprar.", "Atiendo a todos porque no tengo cómo filtrar. Cierro con pocos y acabo agotado."),
            ("No sé si lo que hago está funcionando.", "Publico, invierto, pruebo. Pero nadie me dice qué está dando resultado y qué es tirar dinero."),
        ],
        closing="No es falta de esfuerzo. Es falta de sistema. Y eso sí se construye.",
        cta="Quiero cambiar esto",
    ),
    transform=dict(
        eyebrow="Imagina esto", title="Dentro de unos meses:",
        items=[
            ("Te despiertas con consultas nuevas.", "Un huésped de Canadá, un comprador de Texas, una familia de Madrid. Llegaron solos, a través de tu presencia digital, mientras tú dormías."),
            ("Te escriben ya confiando en ti.", "Te encontraron en su idioma, vieron quién eres y cómo trabajas. La conversación empieza a mitad de camino."),
            ("Dejas de perseguir clientes.", "Tienes un sistema que capta, filtra y agenda. Tú solo atiendes a quienes de verdad quieren comprar o reservar."),
            ("Tomas decisiones con datos.", "Sabes qué canal trae clientes, cuánto cuesta cada uno y dónde invertir el siguiente peso."),
            ("Y tú te encargas de lo que amas.", "La obra, las propiedades, tus huéspedes. Lo digital ya trabaja para ti, no al revés."),
        ],
        cta="Quiero esto para mi negocio",
    ),
    services=dict(
        eyebrow="Cómo te ayudo a crecer", title="Cinco frentes. Un solo objetivo: que tu negocio atraiga clientes sin depender de ti.",
        sub="Entro donde más duele y construimos desde ahí. No necesitas los cinco desde el día uno.",
        labels=("Lo que hoy te frena", "Lo que hacemos", "Lo que te llevas"),
        items=[
            ("01", "Presencia digital estratégica",
             "Nadie te encuentra en internet, o te encuentran y no te escriben.",
             "Diseño tu web bilingüe pensada para convertir, la posiciono en Google, conecto WhatsApp y automatizo el primer contacto.",
             "Consultas que llegan solas, 24/7, en español e inglés."),
            ("02", "Conexión humana y ventas",
             "No sabes cómo generar confianza con alguien que nunca te verá en persona.",
             "Definimos tu mensaje, tu historia y cada punto de contacto: desde el primer mensaje hasta la firma o la reserva.",
             "Clientes que llegan confiando y cierran más rápido."),
            ("03", "Expansión internacional",
             "Solo atraes clientes locales y sabes que tu mercado es más grande.",
             "Adaptamos tu comunicación al comprador anglo y francófono: idioma, cultura, formas de pago, expectativas.",
             "Acceso real a compradores y huéspedes de otros países."),
            ("04", "Estrategia y crecimiento",
             "Inviertes en marketing sin saber qué funciona.",
             "Analizamos tu negocio, tus números y tus canales. Definimos un plan claro y medimos cada mes.",
             "Decisiones con datos y un crecimiento que se sostiene."),
            ("05", "Libertad operativa",
             "Quieres crecer, pero ya no tienes horas en el día.",
             "Automatizamos lo repetitivo y dejamos un sistema que funciona sin que estés pegado a la pantalla.",
             "Tiempo para operar tu negocio y vivir tu vida."),
        ],
        wheel=dict(hint="Desliza para recorrer los cinco frentes", counter="de"),
        note="Cada proyecto se cotiza después del diagnóstico gratis. Sin paquetes rígidos: lo que tu negocio necesita, en el orden correcto.",
        cta="Agendar diagnóstico gratis",
    ),
    cases=dict(
        eyebrow="Caso real", title="Lo que pasa cuando lo digital trabaja para ti",
        items=[dict(
            client="Tekton Arquitectos", sector="Construcción · Despacho de arquitectura e ingeniería",
            url="https://tektonarquitectos.vercel.app/", url_label="tektonarquitectos.vercel.app",
            challenge="Su web estaba desactualizada y era, justamente, la puerta por donde llegaban sus clientes. Poca presencia en internet y consultas que se perdían en el camino.",
            solution="Modernicé toda su comunicación en línea: nueva web, mensajes claros y un camino directo del visitante al contacto.",
            result="Dejaron de perder a los clientes que ya llegaban por internet, hoy su canal principal de nuevos proyectos.",
            labels=("Reto", "Solución", "Resultado"),
            quote="Nos ayudó a no perder nuestros clientes en línea, que son actualmente los que más nos llegan.",
            author="Alejandro Bautista Hernández", role="Director proyectista, Tekton Arquitectos",
        )],
        view="Ver el sitio", cta="Quiero un resultado así", placeholder="Vista del sitio",
    ),
    about=dict(
        eyebrow="Sobre mí", title="Hola, soy Eros Atzin Martínez Hernández.",
        p=[
            "No soy solo un diseñador web. Soy estratega digital, conector de personas y aprendiz constante. Fundé Eros Studio para acompañar a negocios como el tuyo a crecer más allá de su mercado local.",
            "Vengo del sector inmobiliario y de la construcción. Vi de cerca cómo negocios increíbles dependían solo de referidos, no tenían presencia digital y perdían clientes internacionales por no estar en inglés.",
            "También tuve negocios que fracasaron. Y eso me enseñó más que cualquier éxito: la gente no compra servicios, compra confianza.",
            "Hoy combino estrategia, diseño y conexión humana para que tu negocio atraiga clientes de todo el mundo mientras tú te encargas de lo operativo. Y lo hago desde donde me lleve la vida.",
        ],
        facts=[("Idiomas", "Español · Inglés · Francés (en progreso)"), ("Cómo trabajo", "Contigo, no para ti. Remoto, desde cualquier lugar"), ("Enfoque", "Resultados y claridad, no tecnicismos")],
        cta="Hablemos por WhatsApp",
    ),
    process=dict(
        eyebrow="Proceso", title="Así trabajamos juntos",
        steps=[
            ("Diagnóstico gratis", "15 minutos por WhatsApp o llamada. Entiendo tu negocio, veo tu presencia actual y te digo con honestidad si puedo ayudarte y por dónde empezar."),
            ("Propuesta clara", "Alcance, precio y tiempos por escrito. Sin sorpresas ni letras chiquitas."),
            ("Estrategia y construcción", "Trabajo mientras tú sigues operando. Te mantengo informado con avances reales, no con reportes vacíos."),
            ("Lanzamiento y capacitación", "Te enseño a usar todo. Tu equipo queda autónomo y tú entiendes qué está pasando."),
            ("Acompañamiento", "Si quieres seguir creciendo, seguimos juntos: medimos, ajustamos y escalamos mes a mes."),
        ],
        cta="Empezar con el paso 1",
    ),
    faq=dict(
        eyebrow="Preguntas frecuentes", title="Lo que suelen preguntarme antes de decidir",
        items=[
            ("¿Qué incluye exactamente tu servicio?", "Depende de dónde esté tu negocio. Puede ir desde un diagnóstico con plan de acción, hasta una web bilingüe con sistema de captación, o un acompañamiento mensual de estrategia. En el diagnóstico gratis te digo qué necesitas y qué no."),
            ("¿Cuánto cuesta?", "Cada proyecto se cotiza según su alcance. Te doy un precio exacto y por escrito después del diagnóstico, para que decidas con claridad y sin presión."),
            ("¿Cuánto tiempo tarda?", "Un diagnóstico, una semana. Una presencia digital completa, de 2 a 4 semanas. Un sistema de captación internacional, de 4 a 6. El acompañamiento es mensual."),
            ("¿Qué otros servicios ofreces?", "Además de estrategia y presencia digital: grabación con dron de propiedades, obras y hoteles; edición de video con calidad profesional para redes y web; fotografía de arquitectura e interiores; recorridos virtuales 360°; perfil de Google Business optimizado; gestión de redes sociales; campañas de anuncios en Meta y Google; y redacción bilingüe de textos para tu marca. Todo pensado para que un cliente internacional te vea y confíe."),
            ("¿Trabajas con negocios fuera de Latinoamérica?", "Sí. Trabajo remoto con clientes de cualquier país, en español o inglés."),
            ("¿Cómo medimos resultados?", "Desde el primer día definimos qué vamos a medir: consultas, conversaciones por WhatsApp, reservas o citas. Cada mes ves qué está funcionando, en un lenguaje que entiendes."),
            ("¿Qué pasa si no me gusta el resultado?", "Incluyo rondas de revisión y trabajamos juntos en cada etapa. No lanzamos nada hasta que estés conforme."),
            ("¿Ofreces acompañamiento después?", "Sí. Es opcional y es donde más crecen mis clientes: mantenimiento, contenido, optimización y estrategia mensual."),
        ],
        more="¿Tienes otra pregunta?", cta="Pregúntame por WhatsApp",
    ),
    final=dict(
        title_a="Tu competencia ya recibe clientes de otros países.", title_b="Tú también puedes.",
        sub="Agenda un diagnóstico gratis y en 15 minutos te digo exactamente qué necesita tu negocio para atraer clientes internacionales.",
        cta="Agendar diagnóstico gratis por WhatsApp",
        note="Sin compromiso. Sin presión. Solo claridad para decidir.",
    ),
    footer=dict(
        tag="Crecimiento digital con propósito. Turismo · Inmobiliaria · Construcción.",
        contact="Contacto", nav="Navegación", langs="Idioma",
        rights="Todos los derechos reservados.", made="Diseñado y desarrollado por Eros Atzin Martínez Hernández.",
        top="Volver arriba",
    ),
    float_label="¿Hablamos?", float_aria="Abrir WhatsApp para agendar diagnóstico",
)

EN = dict(
    lang="en", other_lang="ES", other_lang_label="Español", other_href="../index.html",
    prefix="../", canonical=SITE_URL + "/en/",
    title=f"{NAME} | Eros Studio — Digital growth for tourism, real estate and construction",
    description=("Eros Atzin Martínez Hernández, founder of Eros Studio. I help boutique hotels, real estate agencies and construction "
                 "companies build a business that attracts clients from all over the world — bilingual digital presence, human connection "
                 "and international expansion — while you run operations. Free diagnosis on WhatsApp."),
    keywords="Eros Atzin Martínez Hernández, Eros Studio, digital growth, digital strategy for real estate, marketing for construction companies, marketing for boutique hotels, bilingual websites, international clients, Mexico",
    wa_msg="Hi Eros, I saw your website and I'd like to book a free diagnosis for my business.",
    skip="Skip to content",
    nav=dict(growth="Growth", services="How I help", cases="Work", about="About", process="Process", faq="FAQ", cta="Book a diagnosis", menu="Menu"),
    chapters=["Home", "Manifesto", "Your situation", "Imagine", "How I help", "Real work", "About", "Process", "Questions", "Let's start"],
    intro_aria="Loading Eros Studio",
    hero=dict(
        eyebrow="Eros Atzin Martínez Hernández · Eros Studio",
        h1_a="Your business can attract clients from", h1_b="all over the world", h1_c="while you focus on running it.",
        sub="For boutique hotels, real estate agencies and construction companies that want to grow beyond their local market.",
        cta="Book a free diagnosis", cta2="See how it works",
        trust=["Free 15-minute diagnosis", "Reply within 24 h"],
        scroll="Scroll",
        big_a="EROS", big_b="ATZIN",
        role="Strategy · Digital presence · Expansion",
        sig_line="I don't sell you a website. I walk with you while you build a business that grows.",
    ),
    trust=dict(label="Experience in", items=["Tourism", "Real estate", "Construction", "Tekton Arquitectos", "Spanish", "English", "French (in progress)"],
               years="3+ years inside real estate and construction"),
    manifesto=dict(
        eyebrow="Manifesto",
        text="A pretty website doesn't pay the payroll. What pays the payroll is a business people can find, trust and buy from, even from ten thousand kilometres away. That is what we build together.",
        stats=[("3+", "years in real estate and construction"), ("2", "languages to sell in, a third on the way"), ("24/7", "your business capturing leads while you operate")],
    ),
    problem=dict(
        eyebrow="Your situation", title="If any of these sound like your own voice, keep reading.",
        items=[
            ("I depend on referrals.", "If nobody recommends me one month, nobody comes in that month. And I have no way to change it."),
            ("My website doesn't bring me a single client.", "I paid for it, it exists, but nobody arrives through it. I don't even know if it shows up on Google."),
            ("Foreign clients can't find me.", "I know there are international buyers and guests with budget. But everything I have is only in Spanish."),
            ("I waste hours on people who won't buy.", "I talk to everyone because I have no way to filter. I close with few and end up exhausted."),
            ("I don't know if what I'm doing is working.", "I post, I invest, I try things. But nobody tells me what's paying off and what's throwing money away."),
        ],
        closing="It's not a lack of effort. It's a lack of a system. And that can be built.",
        cta="I want to change this",
    ),
    transform=dict(
        eyebrow="Imagine this", title="A few months from now:",
        items=[
            ("You wake up to new enquiries.", "A guest from Canada, a buyer from Texas, a family from Madrid. They arrived on their own, through your digital presence, while you slept."),
            ("They write to you already trusting you.", "They found you in their language, saw who you are and how you work. The conversation starts halfway there."),
            ("You stop chasing clients.", "You have a system that captures, filters and books. You only talk to people who truly want to buy or reserve."),
            ("You make decisions with data.", "You know which channel brings clients, what each one costs and where to invest the next dollar."),
            ("And you focus on what you love.", "The build, the properties, your guests. Digital now works for you, not the other way around."),
        ],
        cta="I want this for my business",
    ),
    services=dict(
        eyebrow="How I help you grow", title="Five fronts. One goal: a business that attracts clients without depending on you.",
        sub="I start where it hurts most and we build from there. You don't need all five from day one.",
        labels=("What's holding you back", "What we do", "What you get"),
        items=[
            ("01", "Strategic digital presence",
             "Nobody finds you online, or they find you and don't reach out.",
             "I design your bilingual website built to convert, rank it on Google, connect WhatsApp and automate the first contact.",
             "Enquiries that arrive on their own, 24/7, in Spanish and English."),
            ("02", "Human connection and sales",
             "You don't know how to build trust with someone who will never meet you in person.",
             "We define your message, your story and every touchpoint: from the first message to the signature or the booking.",
             "Clients who arrive trusting you and close faster."),
            ("03", "International expansion",
             "You only attract local clients and you know your market is bigger.",
             "We adapt your communication to English- and French-speaking buyers: language, culture, payment methods, expectations.",
             "Real access to buyers and guests from other countries."),
            ("04", "Strategy and growth",
             "You invest in marketing without knowing what works.",
             "We analyse your business, your numbers and your channels. We set a clear plan and measure every month.",
             "Data-driven decisions and growth that holds."),
            ("05", "Operational freedom",
             "You want to grow, but you have no hours left in the day.",
             "We automate the repetitive and leave you a system that runs without you glued to a screen.",
             "Time to run your business and live your life."),
        ],
        wheel=dict(hint="Scroll to explore the five fronts", counter="of"),
        note="Every project is quoted after the free diagnosis. No rigid packages: what your business needs, in the right order.",
        cta="Book a free diagnosis",
    ),
    cases=dict(
        eyebrow="Real work", title="What happens when digital works for you",
        items=[dict(
            client="Tekton Arquitectos", sector="Construction · Architecture & engineering firm",
            url="https://tektonarquitectos.vercel.app/", url_label="tektonarquitectos.vercel.app",
            challenge="Their website was outdated and it was, precisely, the door their clients came through. Little online presence and enquiries getting lost along the way.",
            solution="I modernised their entire online communication: a new website, clear messaging and a direct path from visitor to contact.",
            result="They stopped losing the clients already arriving online, now their main channel for new projects.",
            labels=("Challenge", "Solution", "Result"),
            quote="He helped us stop losing our online clients, who are currently the ones that reach us the most.",
            author="Alejandro Bautista Hernández", role="Design Director, Tekton Arquitectos",
        )],
        view="Visit the site", cta="I want a result like this", placeholder="Site preview",
    ),
    about=dict(
        eyebrow="About", title="Hi, I'm Eros Atzin Martínez Hernández.",
        p=[
            "I'm not just a web designer. I'm a digital strategist, a connector of people and a constant learner. I founded Eros Studio to walk alongside businesses like yours as they grow beyond their local market.",
            "I come from real estate and construction. I saw first-hand how incredible businesses relied only on referrals, had no digital presence and lost international clients for not being in English.",
            "I've also had businesses that failed. And that taught me more than any success: people don't buy services, they buy trust.",
            "Today I combine strategy, design and human connection so your business attracts clients from all over the world while you run operations. And I do it from wherever life takes me.",
        ],
        facts=[("Languages", "Spanish · English · French (in progress)"), ("How I work", "With you, not for you. Remote, from anywhere"), ("Focus", "Results and clarity, not jargon")],
        cta="Let's talk on WhatsApp",
    ),
    process=dict(
        eyebrow="Process", title="This is how we work together",
        steps=[
            ("Free diagnosis", "15 minutes on WhatsApp or a call. I get to know your business, look at your current presence and tell you honestly whether I can help and where to start."),
            ("Clear proposal", "Scope, price and timeline in writing. No surprises, no fine print."),
            ("Strategy and build", "I work while you keep operating. I keep you posted with real progress, not empty reports."),
            ("Launch and training", "I show you how to use everything. Your team becomes autonomous and you understand what's happening."),
            ("Ongoing partnership", "If you want to keep growing, we keep going: measure, adjust and scale month by month."),
        ],
        cta="Start with step 1",
    ),
    faq=dict(
        eyebrow="FAQ", title="What people ask me before deciding",
        items=[
            ("What exactly does your service include?", "It depends on where your business is. It can range from a diagnosis with an action plan, to a bilingual website with a lead-capture system, to monthly strategic support. In the free diagnosis I tell you what you need and what you don't."),
            ("How much does it cost?", "Each project is quoted by scope. You get an exact price in writing after the diagnosis, so you can decide with clarity and no pressure."),
            ("How long does it take?", "A diagnosis, one week. A complete digital presence, 2 to 4 weeks. An international lead-capture system, 4 to 6. Ongoing support is monthly."),
            ("What other services do you offer?", "Beyond strategy and digital presence: drone footage of properties, sites and hotels; professional-grade video editing for social media and web; architecture and interior photography; 360° virtual tours; optimised Google Business profile; social media management; Meta and Google ad campaigns; and bilingual copywriting for your brand. All designed so an international client sees you and trusts you."),
            ("Do you work with businesses outside Latin America?", "Yes. I work remotely with clients from any country, in Spanish or English."),
            ("How do we measure results?", "From day one we define what we'll measure: enquiries, WhatsApp conversations, bookings or appointments. Every month you see what's working, in language you understand."),
            ("What if I don't like the result?", "Revision rounds are included and we work together at every stage. Nothing launches until you're happy."),
            ("Do you offer ongoing support afterwards?", "Yes. It's optional and it's where my clients grow the most: maintenance, content, optimisation and monthly strategy."),
        ],
        more="Got another question?", cta="Ask me on WhatsApp",
    ),
    final=dict(
        title_a="Your competitors already get clients from other countries.", title_b="So can you.",
        sub="Book a free diagnosis and in 15 minutes I'll tell you exactly what your business needs to attract international clients.",
        cta="Book a free diagnosis on WhatsApp",
        note="No commitment. No pressure. Just clarity to decide.",
    ),
    footer=dict(
        tag="Digital growth with purpose. Tourism · Real estate · Construction.",
        contact="Contact", nav="Navigation", langs="Language",
        rights="All rights reserved.", made="Designed and built by Eros Atzin Martínez Hernández.",
        top="Back to top",
    ),
    float_label="Let's talk?", float_aria="Open WhatsApp to book a diagnosis",
)
